# Creating numpy/ n-d arrays


## To numpy liabrary first you have to import.

### There are 6 ways to create Numpy Array
### Method # 01

In [7]:
import numpy as np

In [8]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [9]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

#### arr1 is 1D array and arr2 is 2D array
#### Note: 1D array is also known as Vector

In [11]:
arr3 = np.zeros((3,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
arr4 = np.ones((2,2))
arr4

array([[1., 1.],
       [1., 1.]])

In [16]:
arr5 = np.identity(2)
arr5

array([[1., 0.],
       [0., 1.]])

In [20]:
arr6 = np.arange(10)
arr6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [21]:
arr7 = np.arange(7,21)
arr7

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [22]:
arr8 = np.arange(5,20,2)
arr8

array([ 5,  7,  9, 11, 13, 15, 17, 19])

#### In arr8 the third value is using just like a jumping varaible

In [24]:
arr9 = arr8.copy()
arr9

array([ 5,  7,  9, 11, 13, 15, 17, 19])